get_users:
    path:      /users
    defaults:  { _controller: MainUserBundle:Users:getUsers }
    methods:  [GET]

get_users_list:
    path:      /users/list
    defaults:  { _controller: MainUserBundle:Users:getUsersList }
    methods:  [GET]

get_user:
    path:      /users/{id}
    defaults:  { _controller: MainUserBundle:Users:getUser }
    methods:  [GET]

edit_user:
    path:      /users/{id}/edit
    defaults:  { _controller: MainUserBundle:Users:editUser }
    methods:  [GET]

put_user:
    path:      /users/{id}/
    defaults:  { _controller: MainUserBundle:Users:putUser }
    methods:  [PUT]

remove_user:
    path:      /users/{id}/remove
    defaults:  { _controller: MainUserBundle:Users:removeUser }
    methods:  [GET]