main_user:
    resource: "@MainUserBundle/Controller/"
    type:     annotation
    prefix:   /

main_admin:
    resource: "@MainAdminBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

dashboard:
    path:      /
    defaults:  { _controller: MainAdminBundle:Default:show }

users:
    resource: "@MainAdminBundle/Resources/config/routing/users.yml"

userProfile:
    resource: "@MainAdminBundle/Resources/config/routing/userProfile.yml"

widgets:
    resource: "@MainAdminBundle/Resources/config/routing/widgets.yml"

databases:
    resource: "@MainAdminBundle/Resources/config/routing/databases.yml"

api:
    resource: "@MainAdminBundle/Resources/config/routing/api.yml"

fake_generator:
    path:      /fakeJson
    defaults:  { _controller: MainAdminBundle:Helper:getFakeJson, _format: json }
    requirements: { _format: (json), _method: GET }

fake_generator2:
    path:      /fakeJson2
    defaults:  { _controller: MainAdminBundle:Helper:getFakeJson2, _format: json }
    requirements: { _format: (json), _method: GET }