# BASIC REST====================

get_databases: #Symfony view
    path:      /databases
    defaults:  { _controller: MainAdminBundle:Databases:getDatabases }
    methods:  [GET]

get_databases_list: #API #Angular REST
    path:      /databases/list
    defaults:  { _controller: MainAdminBundle:Databases:getDatabasesList, _format: 'json' }
    methods:  [GET]

new_database: #Symfony view
    path:      /databases/new
    defaults:  { _controller: MainAdminBundle:Databases:new }
    methods:  [GET]

save_database: #Angular REST
    path:      /databases/save
    defaults:  { _controller: MainAdminBundle:Databases:save }
    methods:  [POST]

patch_database: #Angular REST
    path:      /databases/patch/{id}
    defaults:  { _controller: MainAdminBundle:Databases:patch }
    methods:  [POST]

get_database: #API #Angular REST
    path:      /databases/{id}
    defaults:  { _controller: MainAdminBundle:Databases:get, _format: 'json' }
    methods:  [GET]
    requirements:
        id: \d+

edit_database: #Symfony view
    path:      /databases/{id}/edit
    defaults:  { _controller: MainAdminBundle:Databases:edit }
    methods:  [GET]
    requirements:
        id: \d+

remove_database: #Angular REST
    path:      /databases/{id}/remove
    defaults:  { _controller: MainAdminBundle:Databases:remove }
    methods:  [DELETE]
    requirements:
        id: \d+

# END OF BASIC REST====================

get_database_tables: #Angular REST
    path:      /databases/tables/list
    defaults:  { _controller: MainAdminBundle:Databases:tablesList }
    methods:  [GET]

get_database_views: #Angular REST
    path:      /databases/views/list
    defaults:  { _controller: MainAdminBundle:Databases:viewsList }
    methods:  [GET]

get_database_functions: #Angular REST
    path:      /databases/functions/list
    defaults:  { _controller: MainAdminBundle:Databases:functionsList }
    methods:  [GET]

get_database_table_definition: #Angular REST
    path:      /databases/table/{name}
    defaults:  { _controller: MainAdminBundle:Databases:tableDefinition }
    methods:  [GET]
