get_userProfile:
    path:      /userProfile/{id}/show
    defaults:  { _controller: MainAdminBundle:UserProfile:index }
    methods:  [GET]

edit_userProfile:
    path:      /userProfile/{id}/edit
    defaults:  { _controller: MainAdminBundle:UserProfile:editUserProfile }
    methods:  [POST]

get_userProfile_id:
    path:      /userProfile/{id}
    defaults:  { _controller: MainAdminBundle:UserProfile:getUserProfile }
    methods:  [GET]

put_userProfile:
    path:      /userProfile/{id}/
    defaults:  { _controller: MainAdminBundle:UserProfile:putUserProfile }
    methods:  [PUT]
