show_userProfile:
    path:      /userProfile/{id}/show
    defaults:  { _controller: MainAdminBundle:UserProfile:index }
    methods:  [GET]

edit_userProfile:
    path:      /userProfile/{id}/edit
    defaults:  { _controller: MainAdminBundle:UserProfile:edit }
    methods:  [POST]

get_userProfile:
    path:      /userProfile/{id}
    defaults:  { _controller: MainAdminBundle:UserProfile:get }
    methods:  [GET]

put_userProfile:
    path:      /userProfile/{id}/
    defaults:  { _controller: MainAdminBundle:UserProfile:put }
    methods:  [PUT]

delete_userProfile:
    path:      /userProfile/{id}/
    defaults:  { _controller: MainAdminBundle:UserProfile:delete }
    methods:  [DELETE]