assetic:
    assets:
        img_bootstrap_glyphicons_woff:
            inputs:
                -  '%kernel.root_dir%/../web/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'
        img_bootstrap_glyphicons_svg:
            inputs:
                -  '%kernel.root_dir%/../web/fonts/glyphicons-halflings-regular.svg'
            output: 'fonts/glyphicons-halflings-regular.svg'
        img_bootstrap_glyphicons_eot:
            inputs:
                -  '%kernel.root_dir%/../web/fonts/glyphicons-halflings-regular.eot'
            output: 'fonts/glyphicons-halflings-regular.eot'
        img_bootstrap_glyphicons_ttf:
            inputs:
                -  '%kernel.root_dir%/../web/fonts/glyphicons-halflings-regular.ttf'
            output: 'fonts/glyphicons-halflings-regular.ttf'
        font_awesome_woff:
            inputs:
                -  '%kernel.root_dir%/../web/assets/vendor/font-awesome/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'
        layout:
            inputs:
                -  '@MainAdminBundle/Resources/public/css/layout.min.css'
                -  '@MainAdminBundle/Resources/public/css/main.css'
        angular_datatables_css:
            inputs:
               - '%kernel.root_dir%/../web/assets/vendor/angular-datatables/dist/datatables.bootstrap.css'