bazinga_faker:
    orm: doctrine
    entities:
            Main\UserBundle\Entity\Users:
                number: 35
            Main\AdminBundle\Entity\Widgets:
                number: 35
            Main\AdminBundle\Entity\Databases:
                number: 30
                custom_formatters:
                    address: { method: localIpv4 }
                    port: { method: randomNumber, parameters: [4] }