get_users:
    path:      /userProfile
    defaults:  { _controller: MainUserBundle:Users:getUserProfile }
    methods:  [GET]

get_user:
    path:      /userProfile/{id}
    defaults:  { _controller: MainUserBundle:Users:getUserProfile }
    methods:  [GET]

edit_user:
    path:      /userProfile/{id}/edit
    defaults:  { _controller: MainUserBundle:Users:editUserProfile }
    methods:  [GET]

put_user:
    path:      /userProfile/{id}/
    defaults:  { _controller: MainUserBundle:Users:putUserProfile }
    methods:  [PUT]
