<?php

namespace Main\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatabasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatabasesRepository extends EntityRepository
{
}
