<?php

namespace Main\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WidgetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetsRepository extends EntityRepository
{
}
